# See: https://jekyllrb.com/docs/continuous-integration/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
language: ruby
notifications:
  email: false
sudo: false # route your build to the container-based infrastructure for a faster build
rvm:
- 2.6.3

before_install: gem install bundler
script: ./script/cibuild
